"use client"

import * as React from "react"
import { Button } from "@/components/ui/button"
import {
  Drawer,
  DrawerContent,
  DrawerHeader,
  DrawerTitle,
  DrawerDescription,
  DrawerFooter,
  DrawerClose,
} from "@/components/ui/drawer"
import { FieldRenderer } from "./FieldRenderer"
import type { ColumnSchemaExtended, CollectionData } from "./types"

interface EditFormProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  collection: string
  record: CollectionData | null
  schema: ColumnSchemaExtended[]
  editData: Record<string, any>
  editError: string | null
  priceInputs: Record<string, string>
  setPriceInputs: React.Dispatch<React.SetStateAction<Record<string, string>>>
  onFieldChange: (fieldName: string, value: any) => void
  onSubmit: (e: React.FormEvent) => void
  search?: string
  isAutoGeneratedField: (fieldName: string, hasRelation?: boolean) => boolean
}

export function EditForm({
  open,
  onOpenChange,
  collection,
  record,
  schema,
  editData,
  editError,
  priceInputs,
  setPriceInputs,
  onFieldChange,
  onSubmit,
  search,
  isAutoGeneratedField,
}: EditFormProps) {
  const fields = React.useMemo(
    () => schema.filter((f) => !isAutoGeneratedField(f.name, !!f.relation) && !f.primary && !f.hidden),
    [schema, isAutoGeneratedField]
  )

  const statusField = fields.find(f => f.name === 'status_name')
  const categoryField = fields.find(f => f.name === 'category')
  const nameFieldRu = fields.find(f => f.name === 'title.ru')
  const nameFieldEn = fields.find(f => f.name === 'title.en')
  const priceField = fields.find(f => f.name === 'dataIn.price')
  const weightField = fields.find(f => f.name === 'dataIn.weight')
  const descriptionFieldRu = fields.find(f => f.name === 'dataIn.description.ru')
  const descriptionFieldEn = fields.find(f => f.name === 'dataIn.description.en')
  const excerptFieldRu = fields.find(f => f.name === 'dataIn.excerpt.ru')
  const excerptFieldEn = fields.find(f => f.name === 'dataIn.excerpt.en')
  const imagesField = fields.find(f => f.name === 'dataIn.images')
  
  // Details fields
  const detailsCollectionRu = fields.find(f => f.name === 'dataIn.details.collection.ru')
  const detailsCollectionEn = fields.find(f => f.name === 'dataIn.details.collection.en')
  const detailsSilhouetteRu = fields.find(f => f.name === 'dataIn.details.silhouette.ru')
  const detailsSilhouetteEn = fields.find(f => f.name === 'dataIn.details.silhouette.en')
  const detailsTextileRu = fields.find(f => f.name === 'dataIn.details.textile.ru')
  const detailsTextileEn = fields.find(f => f.name === 'dataIn.details.textile.en')
  const detailsFinishingRu = fields.find(f => f.name === 'dataIn.details.finishing.ru')
  const detailsFinishingEn = fields.find(f => f.name === 'dataIn.details.finishing.en')
  const detailsRecommendedActivitiesRu = fields.find(f => f.name === 'dataIn.details.recommendedActivities.ru')
  const detailsRecommendedActivitiesEn = fields.find(f => f.name === 'dataIn.details.recommendedActivities.en')
  const detailsSizesInStock = fields.find(f => f.name === 'dataIn.details.sizesInStock')

  const otherFields = fields.filter(f =>
    f.name !== 'status_name' &&
    f.name !== 'category' &&
    f.name !== 'title.ru' &&
    f.name !== 'title.en' &&
    f.name !== 'dataIn.price' &&
    f.name !== 'dataIn.weight' &&
    f.name !== 'dataIn.description' &&
    f.name !== 'dataIn.description.ru' &&
    f.name !== 'dataIn.description.en' &&
    f.name !== 'dataIn.excerpt.ru' &&
    f.name !== 'dataIn.excerpt.en' &&
    f.name !== 'dataIn.images' &&
    !f.name.startsWith('dataIn.details.')
  )

  const isTextsCollection = collection === 'texts'
  const isProductsCollection = collection === 'products'
  const [selectedLocale, setSelectedLocale] = React.useState<'ru' | 'en'>('ru')
  
  return (
    <Drawer open={open} onOpenChange={onOpenChange} direction="right">
      <DrawerContent 
        direction="right" 
        className={`h-full overflow-y-auto overflow-x-hidden ${isProductsCollection ? 'w-full max-w-[50vw]' : 'w-full max-w-md'}`}
      >
        <DrawerHeader className="px-5 pt-5 pb-0">
          <DrawerTitle>Edit record in {collection}</DrawerTitle>
          <DrawerDescription>
            Change fields below. Auto-generated fields are not editable and hidden.
          </DrawerDescription>
        </DrawerHeader>
        {isProductsCollection && (
          <div className="px-5 pt-4 pb-2">
            <div className="flex gap-2">
              <Button
                type="button"
                variant={selectedLocale === 'ru' ? 'default' : 'outline'}
                size="sm"
                onClick={() => setSelectedLocale('ru')}
                className="h-8 px-3 rounded-md font-sans text-xs"
              >
                RU
              </Button>
              <Button
                type="button"
                variant={selectedLocale === 'en' ? 'default' : 'outline'}
                size="sm"
                onClick={() => setSelectedLocale('en')}
                className="h-8 px-3 rounded-md font-sans text-xs"
              >
                EN
              </Button>
            </div>
          </div>
        )}
        <form onSubmit={onSubmit} className={`space-y-4 px-5 py-4 ${isTextsCollection ? 'flex-1 overflow-y-auto pb-24' : 'flex-1 overflow-y-auto'} w-full max-w-full overflow-x-hidden`} noValidate>
          {/* Status and Category in one row */}
          {(statusField || categoryField) && (
            <div className="grid grid-cols-2 gap-4">
              {statusField && (
                <div className="flex flex-col gap-2">
                  <FieldRenderer
                    field={statusField}
                    value={editData[statusField.name]}
                    onChange={(value) => onFieldChange(statusField.name, value)}
                    dialogType="edit"
                    priceInputs={priceInputs}
                    setPriceInputs={setPriceInputs}
                    search={search}
                  />
                </div>
              )}
              {categoryField && (
                <div className="flex flex-col gap-2">
                  <FieldRenderer
                    field={categoryField}
                    value={editData[categoryField.name]}
                    onChange={(value) => onFieldChange(categoryField.name, value)}
                    dialogType="edit"
                    priceInputs={priceInputs}
                    setPriceInputs={setPriceInputs}
                    search={search}
                  />
                </div>
              )}
            </div>
          )}

          {/* Name fields - show based on selected locale for products */}
          {isProductsCollection ? (
            <>
              {selectedLocale === 'ru' && nameFieldRu && (
                <div className="flex flex-col gap-2">
                  <FieldRenderer
                    field={nameFieldRu}
                    value={editData[nameFieldRu.name]}
                    onChange={(value) => onFieldChange(nameFieldRu.name, value)}
                    dialogType="edit"
                    priceInputs={priceInputs}
                    setPriceInputs={setPriceInputs}
                    search={search}
                  />
                </div>
              )}
              {selectedLocale === 'en' && nameFieldEn && (
                <div className="flex flex-col gap-2">
                  <FieldRenderer
                    field={nameFieldEn}
                    value={editData[nameFieldEn.name]}
                    onChange={(value) => onFieldChange(nameFieldEn.name, value)}
                    dialogType="edit"
                    priceInputs={priceInputs}
                    setPriceInputs={setPriceInputs}
                    search={search}
                  />
                </div>
              )}
            </>
          ) : (
            nameFieldRu && (
              <div className="flex flex-col gap-2">
                <FieldRenderer
                  field={nameFieldRu}
                  value={editData[nameFieldRu.name]}
                  onChange={(value) => onFieldChange(nameFieldRu.name, value)}
                  dialogType="edit"
                  priceInputs={priceInputs}
                  setPriceInputs={setPriceInputs}
                  search={search}
                />
              </div>
            )
          )}

          {/* Price field */}
          {priceField && (
            <div className="flex flex-col gap-2">
              <FieldRenderer
                field={priceField}
                value={editData[priceField.name]}
                onChange={(value) => onFieldChange(priceField.name, value)}
                dialogType="edit"
                priceInputs={priceInputs}
                setPriceInputs={setPriceInputs}
                search={search}
              />
            </div>
          )}

          {/* Description fields - show based on selected locale for products */}
          {isProductsCollection ? (
            <>
              {selectedLocale === 'ru' && descriptionFieldRu && (
                <div className="flex flex-col gap-2">
                  <FieldRenderer
                    field={descriptionFieldRu}
                    value={editData[descriptionFieldRu.name]}
                    onChange={(value) => onFieldChange(descriptionFieldRu.name, value)}
                    dialogType="edit"
                    priceInputs={priceInputs}
                    setPriceInputs={setPriceInputs}
                    search={search}
                  />
                </div>
              )}
              {selectedLocale === 'en' && descriptionFieldEn && (
                <div className="flex flex-col gap-2">
                  <FieldRenderer
                    field={descriptionFieldEn}
                    value={editData[descriptionFieldEn.name]}
                    onChange={(value) => onFieldChange(descriptionFieldEn.name, value)}
                    dialogType="edit"
                    priceInputs={priceInputs}
                    setPriceInputs={setPriceInputs}
                    search={search}
                  />
                </div>
              )}
              {/* Excerpt fields */}
              {selectedLocale === 'ru' && excerptFieldRu && (
                <div className="flex flex-col gap-2">
                  <FieldRenderer
                    field={excerptFieldRu}
                    value={editData[excerptFieldRu.name]}
                    onChange={(value) => onFieldChange(excerptFieldRu.name, value)}
                    dialogType="edit"
                    priceInputs={priceInputs}
                    setPriceInputs={setPriceInputs}
                    search={search}
                  />
                </div>
              )}
              {selectedLocale === 'en' && excerptFieldEn && (
                <div className="flex flex-col gap-2">
                  <FieldRenderer
                    field={excerptFieldEn}
                    value={editData[excerptFieldEn.name]}
                    onChange={(value) => onFieldChange(excerptFieldEn.name, value)}
                    dialogType="edit"
                    priceInputs={priceInputs}
                    setPriceInputs={setPriceInputs}
                    search={search}
                  />
                </div>
              )}
            </>
          ) : (
            descriptionFieldRu && (
              <div className="flex flex-col gap-2">
                <FieldRenderer
                  field={descriptionFieldRu}
                  value={editData[descriptionFieldRu.name]}
                  onChange={(value) => onFieldChange(descriptionFieldRu.name, value)}
                  dialogType="edit"
                  priceInputs={priceInputs}
                  setPriceInputs={setPriceInputs}
                  search={search}
                />
              </div>
            )
          )}

          {/* Images field */}
          {imagesField && (
            <div className="flex flex-col gap-2">
              <FieldRenderer
                field={imagesField}
                value={editData[imagesField.name]}
                onChange={(value) => onFieldChange(imagesField.name, value)}
                dialogType="edit"
                priceInputs={priceInputs}
                setPriceInputs={setPriceInputs}
                search={search}
              />
            </div>
          )}

          {/* Details section for products */}
          {isProductsCollection && (
            <div className="space-y-4 pt-4 border-t">
              <h3 className="text-lg font-semibold">Детали продукта</h3>
              
              {/* Collection */}
              {selectedLocale === 'ru' && detailsCollectionRu && (
                <div className="flex flex-col gap-2">
                  <FieldRenderer
                    field={detailsCollectionRu}
                    value={editData[detailsCollectionRu.name]}
                    onChange={(value) => onFieldChange(detailsCollectionRu.name, value)}
                    dialogType="edit"
                    priceInputs={priceInputs}
                    setPriceInputs={setPriceInputs}
                    search={search}
                  />
                </div>
              )}
              {selectedLocale === 'en' && detailsCollectionEn && (
                <div className="flex flex-col gap-2">
                  <FieldRenderer
                    field={detailsCollectionEn}
                    value={editData[detailsCollectionEn.name]}
                    onChange={(value) => onFieldChange(detailsCollectionEn.name, value)}
                    dialogType="edit"
                    priceInputs={priceInputs}
                    setPriceInputs={setPriceInputs}
                    search={search}
                  />
                </div>
              )}

              {/* Silhouette */}
              {selectedLocale === 'ru' && detailsSilhouetteRu && (
                <div className="flex flex-col gap-2">
                  <FieldRenderer
                    field={detailsSilhouetteRu}
                    value={editData[detailsSilhouetteRu.name]}
                    onChange={(value) => onFieldChange(detailsSilhouetteRu.name, value)}
                    dialogType="edit"
                    priceInputs={priceInputs}
                    setPriceInputs={setPriceInputs}
                    search={search}
                  />
                </div>
              )}
              {selectedLocale === 'en' && detailsSilhouetteEn && (
                <div className="flex flex-col gap-2">
                  <FieldRenderer
                    field={detailsSilhouetteEn}
                    value={editData[detailsSilhouetteEn.name]}
                    onChange={(value) => onFieldChange(detailsSilhouetteEn.name, value)}
                    dialogType="edit"
                    priceInputs={priceInputs}
                    setPriceInputs={setPriceInputs}
                    search={search}
                  />
                </div>
              )}

              {/* Textile */}
              {selectedLocale === 'ru' && detailsTextileRu && (
                <div className="flex flex-col gap-2">
                  <FieldRenderer
                    field={detailsTextileRu}
                    value={editData[detailsTextileRu.name]}
                    onChange={(value) => onFieldChange(detailsTextileRu.name, value)}
                    dialogType="edit"
                    priceInputs={priceInputs}
                    setPriceInputs={setPriceInputs}
                    search={search}
                  />
                </div>
              )}
              {selectedLocale === 'en' && detailsTextileEn && (
                <div className="flex flex-col gap-2">
                  <FieldRenderer
                    field={detailsTextileEn}
                    value={editData[detailsTextileEn.name]}
                    onChange={(value) => onFieldChange(detailsTextileEn.name, value)}
                    dialogType="edit"
                    priceInputs={priceInputs}
                    setPriceInputs={setPriceInputs}
                    search={search}
                  />
                </div>
              )}

              {/* Finishing */}
              {selectedLocale === 'ru' && detailsFinishingRu && (
                <div className="flex flex-col gap-2">
                  <FieldRenderer
                    field={detailsFinishingRu}
                    value={editData[detailsFinishingRu.name]}
                    onChange={(value) => onFieldChange(detailsFinishingRu.name, value)}
                    dialogType="edit"
                    priceInputs={priceInputs}
                    setPriceInputs={setPriceInputs}
                    search={search}
                  />
                </div>
              )}
              {selectedLocale === 'en' && detailsFinishingEn && (
                <div className="flex flex-col gap-2">
                  <FieldRenderer
                    field={detailsFinishingEn}
                    value={editData[detailsFinishingEn.name]}
                    onChange={(value) => onFieldChange(detailsFinishingEn.name, value)}
                    dialogType="edit"
                    priceInputs={priceInputs}
                    setPriceInputs={setPriceInputs}
                    search={search}
                  />
                </div>
              )}

              {/* Recommended Activities */}
              {selectedLocale === 'ru' && detailsRecommendedActivitiesRu && (
                <div className="flex flex-col gap-2">
                  <FieldRenderer
                    field={detailsRecommendedActivitiesRu}
                    value={editData[detailsRecommendedActivitiesRu.name]}
                    onChange={(value) => onFieldChange(detailsRecommendedActivitiesRu.name, value)}
                    dialogType="edit"
                    priceInputs={priceInputs}
                    setPriceInputs={setPriceInputs}
                    search={search}
                  />
                </div>
              )}
              {selectedLocale === 'en' && detailsRecommendedActivitiesEn && (
                <div className="flex flex-col gap-2">
                  <FieldRenderer
                    field={detailsRecommendedActivitiesEn}
                    value={editData[detailsRecommendedActivitiesEn.name]}
                    onChange={(value) => onFieldChange(detailsRecommendedActivitiesEn.name, value)}
                    dialogType="edit"
                    priceInputs={priceInputs}
                    setPriceInputs={setPriceInputs}
                    search={search}
                  />
                </div>
              )}

              {/* Sizes in Stock */}
              {detailsSizesInStock && (
                <div className="flex flex-col gap-2">
                  <FieldRenderer
                    field={detailsSizesInStock}
                    value={editData[detailsSizesInStock.name]}
                    onChange={(value) => onFieldChange(detailsSizesInStock.name, value)}
                    dialogType="edit"
                    priceInputs={priceInputs}
                    setPriceInputs={setPriceInputs}
                    search={search}
                  />
                </div>
              )}
            </div>
          )}

          {/* Other fields */}
          {otherFields.map((field) => (
            <div key={field.name} className="flex flex-col gap-2">
              <FieldRenderer
                field={field}
                value={editData[field.name]}
                onChange={(value) => onFieldChange(field.name, value)}
                dialogType="edit"
                priceInputs={priceInputs}
                setPriceInputs={setPriceInputs}
                search={search}
              />
            </div>
          ))}

          {editError && (
            <div className="rounded-lg border border-destructive/50 bg-destructive/10 p-3 text-sm text-destructive">
              {editError}
            </div>
          )}
        </form>
        {isTextsCollection ? (
          <div className="mt-auto border-t bg-background px-5 py-4 sticky bottom-0 z-10">
            <div className="grid grid-cols-2 gap-3 w-full">
              <Button type="button" variant="outline" onClick={() => onOpenChange(false)} className="w-full">
                Отмена
              </Button>
              <Button type="button" onClick={(e) => {
                e.preventDefault()
                console.log('[EditForm] Save button clicked (texts collection)')
                const form = document.querySelector('form')
                if (form) {
                  const formEvent = new Event('submit', { bubbles: true, cancelable: true })
                  form.dispatchEvent(formEvent)
                  onSubmit(e as any)
                }
              }} className="w-full">Сохранить</Button>
            </div>
          </div>
        ) : (
          <DrawerFooter className="p-0">
            <div className="grid grid-cols-2 gap-3 w-full px-5 pb-5">
              <Button type="button" variant="outline" onClick={() => onOpenChange(false)} className="w-full">
                Отмена
              </Button>
              <Button 
                type="button" 
                className="w-full"
                onClick={(e) => {
                  e.preventDefault()
                  console.log('[EditForm] Save button clicked (regular)')
                  const form = document.querySelector('form')
                  if (form) {
                    onSubmit(e as any)
                  }
                }}
              >
                Сохранить
              </Button>
            </div>
          </DrawerFooter>
        )}
        <DrawerClose className="sr-only" />
      </DrawerContent>
    </Drawer>
  )
}


