import { CollectionConfig } from 'payload'

export const Taxonomy: CollectionConfig = {
  slug: 'taxonomy',
  labels: { singular: 'Taxonomy', plural: 'Taxonomies' },
  admin: { useAsTitle: 'name' },
  fields: [
    { name: 'uuid', type: 'text' },
    {
      name: 'entity',
      type: 'select',
      required: true,
      options: [
        { label: 'Channel', value: 'channel' },
        { label: 'City', value: 'city' },
        { label: 'Country', value: 'country' },
        { label: 'Content', value: 'content' },
        { label: 'Currency', value: 'currency' },
        { label: 'Domain', value: 'domain' },
        { label: 'Isic', value: 'isic' },
        { label: 'Sex', value: 'sex' },
        { label: 'Asset', value: 'asset' },
        { label: 'Asset Variant', value: 'asset_variant' },
        { label: 'Base', value: 'base' },
        { label: 'Base Move', value: 'base_move' },
        { label: 'Base Move Route', value: 'base_move_route' },
        { label: 'Contractor', value: 'contractor' },
        { label: 'Deal', value: 'deal' },
        { label: 'Employee', value: 'employee' },
        { label: 'Employee Echelon', value: 'employee_echelon' },
        { label: 'Employee Timesheet', value: 'employee_timesheet' },
        { label: 'Employee Leave', value: 'employee_leave' },
        { label: 'Finance', value: 'finance' },
        { label: 'Goal', value: 'goal' },
        { label: 'Human', value: 'human' },
        { label: 'Identity', value: 'identity' },
        { label: 'Journal', value: 'journal' },
        { label: 'Journal Connection', value: 'journal_connection' },
        { label: 'Journal Generation', value: 'journal_generation' },
        { label: 'Journal System', value: 'journal_system' },
        { label: 'Key', value: 'key' },
        { label: 'Location', value: 'location' },
        { label: 'Message', value: 'message' },
        { label: 'Message Thread', value: 'message_thread' },
        { label: 'Media', value: 'media' },
        { label: 'Notice', value: 'notice' },
        { label: 'Outreach', value: 'outreach' },
        { label: 'Outreach Referral', value: 'outreach_referral' },
        { label: 'Product', value: 'product' },
        { label: 'Product Variant', value: 'product_variant' },
        { label: 'Permission', value: 'permission' },
        { label: 'Qualification', value: 'qualification' },
        { label: 'Relation', value: 'relation' },
        { label: 'Role', value: 'role' },
        { label: 'Role Permission', value: 'role_permission' },
        { label: 'Segment', value: 'segment' },
        { label: 'Setting', value: 'setting' },
        { label: 'Text', value: 'text' },
        { label: 'Text Variant', value: 'text_variant' },
        { label: 'Taxonomy', value: 'taxonomy' },
        { label: 'University', value: 'university' },
        { label: 'User', value: 'user' },
        { label: 'User Ban', value: 'user_ban' },
        { label: 'User Session', value: 'user_session' },
        { label: 'User Verification', value: 'user_verification' },
        { label: 'Vote', value: 'vote' },
        { label: 'Wallet', value: 'wallet' },
        { label: 'Wallet Transaction', value: 'wallet_transaction' },
        { label: 'Expanse', value: 'expanse' },
        { label: 'Yield', value: 'yield' },
        { label: 'Zoo', value: 'zoo' },
      ],
    },
    { name: 'name', type: 'text', required: true },
    { name: 'title', type: 'json' },
    { name: 'category', type: 'json' },
    { name: 'sort_order', type: 'number', defaultValue: 0 },
    { name: 'created_at', type: 'number' },
    { name: 'updated_at', type: 'number' },
    { name: 'deleted_at', type: 'number' },
    { name: 'data_in', type: 'text' },
  ],
}

export default Taxonomy


