export const COLLECTION_GROUPS: Record<string, string[]> = {
  Contacts: [
    'humans',
    'contractors',
  ],
  Sales: [
    'deals',
    'products',
    'product_variants',
    'qualifications',
  ],
  Marketing: [
    'outreaches',
    'outreach_referrals',
    'segments',
    'yields',
  ],
  Projects: [
    'goals',
    'votes',
  ],
  Logistics: [
    'bases',
    'base_moves',
    'base_move_routes',
    'locations',
  ],
  Staff: [
    'employees',
    'echelons',
    'echelon_employees',
    'employee_timesheets',
    'employee_leaves',
    'universities',
  ],
  Finance: [
    'finances',
    'wallets',
    'wallet_transactions',
    'expanses',
  ],
  Content: [
    'assets',
    'asset_variants',
    'texts',
    'text_variants',
    'media',
    'taxonomy',
  ],
  Chats: [
    'message_threads',
    'messages',
    'notices',
  ],
  Admin: [
    'users',
    'roles',
    'permissions',
    'identities',
    'keys',
    'taxonomy',
    'settings',
    'expanses',
    'relations',
  ],
  Logs: [
    'journals',
    'journal_system',
    'journal_generations',
    'journal_connections',
    'user_sessions',
    'user_bans',
    'user_verifications',
    'zoos',
  ],
}
