import type { RoleCabinetNavItem } from "@/components/cabinet/RoleCabinetLayout";

export const MEMBER_NAV_ITEMS: RoleCabinetNavItem[] = [
  { label: "Dashboard", href: "/member", icon: "gauge" },
  { label: "Profile", href: "/member/profile", icon: "user" },
  { label: "Matching", href: "/member/matching", icon: "heart" },
  { label: "Mentor Search", href: "/member/search", icon: "search" },
  { label: "Favorites", href: "/member/favorites", icon: "bookHeart" },
  { label: "Mentor Availability", href: "/member/mentor-availability", icon: "calendarClock" },
  { label: "My Bookings", href: "/member/bookings", icon: "calendarCheck" },
  { label: "Book Session", href: "/member/bookings/book", icon: "clipboardPlus" },
  { label: "Booking Confirmation", href: "/member/bookings/confirmation", icon: "checkCircle2" },
  { label: "Session Preparation", href: "/member/sessions/preparation", icon: "clipboardPlus" },
  { label: "Session Join", href: "/member/sessions/join", icon: "playCircle" },
  { label: "Session Waiting Room", href: "/member/sessions/waiting-room", icon: "videoIcon" },
  { label: "Session Room", href: "/member/sessions/room", icon: "video" },
  { label: "Session Summary", href: "/member/sessions/summary", icon: "bookOpen" },
  { label: "End Session", href: "/member/sessions/end", icon: "videoOff" },
  { label: "Credits", href: "/member/payments/credits", icon: "badgeDollarSign" },
  { label: "Balance", href: "/member/payments/balance", icon: "wallet" },
  { label: "Transactions", href: "/member/payments/history", icon: "dollarSign" },
  { label: "Notifications", href: "/member/notifications", icon: "messageSquare" },
  { label: "Health Overview", href: "/member/health/overview", icon: "heartPulse" },
  { label: "Health Entry", href: "/member/health/entry", icon: "stethoscope" },
  { label: "Wellness Dashboard", href: "/member/health/wellness-dashboard", icon: "activity" },
  { label: "Mood Entry", href: "/member/health/mood-entry", icon: "smile" },
  { label: "Mood History", href: "/member/health/mood-history", icon: "bookOpen" },
  { label: "Medication Adherence", href: "/member/health/medication-adherence", icon: "pill" },
  { label: "Medication Settings", href: "/member/health/medication-settings", icon: "settings" },
  { label: "Sharing Settings", href: "/member/health/sharing-settings", icon: "shieldCheck" },
  { label: "Data Export", href: "/member/health/data-export", icon: "fileDown" },
  { label: "Content Library", href: "/member/content-library", icon: "library" },
  { label: "Journal", href: "/member/journal", icon: "notebookText" },
  { label: "Privacy", href: "/member/privacy", icon: "shieldCheck" },
  { label: "Settings", href: "/member/settings", icon: "settings" },
];

