export const COLLECTION_GROUPS: Record<string, string[]> = {
  System: [
    'users',
    'users_sessions',
    'user_roles',
    'user_bans',
    'user_verifications',
    'roles',
    'role_permissions',
    'permissions',
    'settings',
  ],
  Content: [
    'media',
    'taxonomy',
  ],
  People: [
    'humans',
    'identities',
    'contractors',
  ],
  Organization: [
    'echelons',
    'employees',
    'echelon_employees',
    'employee_leaves',
    'employee_timesheets',
    'bases',
    'base_moves',
    'base_move_routs',
    'locations',
    'universities',
  ],
  Finance: [
    'finances',
    'wallets',
    'wallet_transactions',
    'expanses',
    'deals',
    'deal_products',
  ],
  Products: [
    'products',
    'product_variants',
    'assets',
    'asset_variants',
    'yields',
  ],
  Communication: [
    'messages',
    'message_threads',
    'notices',
    'outreaches',
    'outreach_referrals',
  ],
  Relations: [
    'relations',
    'segments',
    'qualifications',
    'votes',
  ],
  Journal: [
    'journals',
    'journal_connections',
    'journal_generations',
    'journal_systems',
  ],
  Other: [
    'keys',
    'texts',
    'text_variants',
    'zoos',
  ],
}
